import Head from "next/head";
import Button from "../components/Button/Button";
import Card from "../components/Cards/Card";
import Form from "../components/Form/Form";
import EmailInput from "../components/Input/EmailInput";
import PasswordInput from "../components/Input/PasswordInput";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.google.com/specimen/Press+Start+2P?query=press"
        />
      </Head>

      <main className={styles.main}>
        <Button text="get in touch" />
        <Card>card aja</Card>
        <Form>
          <EmailInput />
          <PasswordInput />
          <Button text="login" />
        </Form>
      </main>
    </div>
  );
}
